### ISSUE TITLE
`ontology_viz.py` hangs

### ISSUE THREAD

**Issue by gramian** [usc-isi-i2/ontology-visualization#14]
Calling `ontology_viz.py` it is not responding with output. If I Ctrl+C abort the process, I get the following error:
```
Traceback (most recent call last):
  File "/home/ch/repos2/ontology-visualization/ontology_viz.py", line 23, in <module>
    common_ns = {URIRef(ns) for ns in (RDF, RDFS, SKOS, SCHEMA, XSD, DOAP, FOAF)}
  File "/home/ch/repos2/ontology-visualization/ontology_viz.py", line 23, in <setcomp>
    common_ns = {URIRef(ns) for ns in (RDF, RDFS, SKOS, SCHEMA, XSD, DOAP, FOAF)}
  File "/usr/lib/python3/dist-packages/rdflib/term.py", line 223, in __new__
    if not _is_valid_uri(value):
  File "/usr/lib/python3/dist-packages/rdflib/term.py", line 76, in _is_valid_uri
    if c in uri: return False
  File "/usr/lib/python3/dist-packages/rdflib/namespace.py", line 173, in __getitem__
    return self.term(key)
  File "/usr/lib/python3/dist-packages/rdflib/namespace.py", line 219, in term
    return URIRef("%s_%s" % (self.uri, i))
KeyboardInterrupt
```
However, the fork https://github.com/fatestigma/ontology-visualization works (and immediately responds).
Tested on **Ubuntu 20.04**, with **Python 3.8.10**, and **python3-rdflib 4.2.2-5**.

**Comment by fatestigma** [comment]
The dependency `rdflib` for this repo has been upgrade to `rdflib >= 6.0.0, < 7.0.0`.
